#!/bin/bash

if [[ "$1" == "-a" && "$2" == "3" ]]
then
    CHARSET=--custom-charset1=charsets/no-space.hcchr
fi

hashcat -O -w 4 --markov-hcstat2=markov/huge.hcstat2 --potfile-path=potfile $CHARSET $@
