#!/bin/bash

METHOD=${2-1000}
HASHCAT="./hashcat -m $METHOD"
INPUT=${1-hashes.txt}

if [ ! -f $INPUT ]
then
    echo Create $INPUT
    exit
fi

# List files:
#   passlists/07*.txt -- 1e10

# Rule files:
#   650k.rule -- 6e5

# Speed calculation:
#   Quad RTX 3090 -- 1e15 / hour (brute single hash)
#   2x slower with 400 hashes
#   4x slower with 400 hashes and wordlist+rules

# ordered from fastest to slowest 

# 7e13
$HASHCAT -a 3 --increment --increment-min 1 --increment-max 7 $INPUT '?a?a?a?a?a?a?a?a'

# 1e10 x 3e4 = 3e14
$HASHCAT -a 0 $INPUT passlists/07*.txt -r rules/append-30k.rule

# ~1 hour
$HASHCAT -a 3 $INPUT masks/43200-*.hcmask

# 1e10 x 6e5 = 6e15
$HASHCAT -a 0 $INPUT passlists/07*.txt -r rules/650k.rule

# 7e15
$HASHCAT -a 3 $INPUT '?a?a?a?a?a?a?a?a'
